### ISSUE TITLE
False positives when detecting CORs Request

### ISSUE THREAD

**Issue by binhqx** [asm89/stack-cors#10]
A [discussion](https://github.com/barryvdh/laravel-cors/pull/21) with the developers of [laravel-cors](https://github.com/barryvdh/laravel-cors) and [TrustedProxy](https://github.com/fideloper/TrustedProxy) lead me to believe that there are cases when stack-cors is miss identifying a request as CORS request.

In `CorsService::isCorsRequest()` the request is only check for an existing  'Origin' header.

Should this function not all all check if the contents of the 'Origin' match the Scheme and  host of the request as well?

Example:

```
public function isCorsRequest(Request $request)
{
    return $request->headers->has('Origin') &&
           $request->headers->get('Origin') != $request->getSchemeAndHttpHost();
}
```

Right now, @barryvdh does this check when register his ServiceProvider in [laravel-cors](https://github.com/barryvdh/laravel-cors/blob/master/src/CorsServiceProvider.php#L37). This early cross-origin check seems to be incompatible with other ServiceProviders like @fideloper 's [TrustedProxy](https://github.com/fideloper/TrustedProxy). 

Would it make more sense to do the  cross-origin check in your middleware instead? Or is there a case when CORS hander would need to trigger for a request with matching  scheme and host.

**Comment by wimleers** [comment]
This bug has also been reported against Drupal 8: https://www.drupal.org/node/2853201.
