### ISSUE TITLE
Allow manual override of the Access-Control-Allow-Origin header

### ISSUE THREAD

**Issue by nirarazi** [asm89/stack-cors#14]
Hi, and thanks for the excellent middleware.

I'm thinking about adding a check in the `addActualRequestHeaders()` function, to see if an Access-Control-Allow-Origin header has already been set on the response, and set it in this function only in case it hasn't been set.

Does anyone see any issue (security or other) with this?

I will be happy to provide a pull request if this makes sense to all.

**Comment by asm89** [comment]
Not sure if still relevant, but this is an old issue. Feel free to re-open. :)
