### ISSUE TITLE
More helpful error response

### ISSUE THREAD

**Issue by inanimatt** [asm89/stack-cors#17]
Currently when the policy is violated, only a simple "Not allowed." response is sent. I'd appreciate it if the message was a little more specific, for instance "Access denied by CORS policy". Alternatively, the ability set a custom message or even supply a custom response would be great!

**Comment by asm89** [comment]
👍 if you want to make this configurable https://github.com/asm89/stack-cors/blob/1c803150239fe9393203c06d787fe4ecc4ad0084/src/Asm89/Stack/Cors.php#L55-L57

**Comment by davidbarratt** [comment]
I would instead remove the error responses completely. See #65 65

**Comment by barryvdh** [comment]
We've removed the errors.
