### ISSUE TITLE
Tag new release

### ISSUE THREAD

**Issue by barryvdh** [asm89/stack-cors#24]
Could you tag a new release with the Symfony 3 support please?

**Comment by GrahamCampbell** [comment]
Ping @asm89.

**Comment by barryvdh** [comment]
Sorry to be a bit pushy, but this is blocking the installation for a lot of users (on Laravel 5.2+). So I either need a stable tag, or I need to create/maintain a fork, which isn't really ideal.

**Comment by Sopamo** [comment]
Yeah, we would really like to use the laravel-cors package from barryvdh, but can't due to this issue.

**Comment by GrahamCampbell** [comment]
> Yeah, we would really like to use the laravel-cors package from barryvdh, but can't due to this issue.

Not quite true, but yeh.

**Comment by GrahamCampbell** [comment]
For example, Cachet uses this and laravel 5.2: https://github.com/CachetHQ/Cachet/blob/master/composer.json.

**Comment by Sopamo** [comment]
Oh, wow, I wasn't aware that you could override a package like that with composer. Thanks!

**Comment by GrahamCampbell** [comment]
Yeh, it's not pretty, but it works for now. :)

**Comment by barryvdh** [comment]
I've just forked the classes in my own project :)
