### ISSUE TITLE
New tag for Symfony 3 support

### ISSUE THREAD

**Issue by jsor** [asm89/stack-cors#26]
I'd appreciate a new tag for Symfony 3.x support.

Thanks.

**Comment by alexpott** [comment]
Drupal 8 is considering using this library - https://www.drupal.org/node/1869548. It would great if there was a new tag - perhaps it could be version 1 - half million downloads via packagist perhaps it is time :)

**Comment by asm89** [comment]
Here you go. Released 1.0.0. :) Thanks for the nudge.

https://github.com/asm89/stack-cors/releases/tag/1.0.0

**Comment by dawehner** [comment]
Thanks a ton @asm89 !

**Comment by jsor** [comment]
Thanks!

**Comment by wimleers** [comment]
Thanks! :)

**Comment by alexpott** [comment]
@asm89 Thanks for the very quick response!
