### ISSUE TITLE
Always set `Vary: Origin`

### ISSUE THREAD

**Issue by wimleers** [asm89/stack-cors#49]
Quoting https://github.com/barryvdh/laravel-cors/issues/20:
>  In this case I tend to agree with your story and we should probably always add the `Vary` header. 
> — @asm89 

> If stack-cors is changed to set the Vary header even on requests without an Origin, then this laravel-cors will need to be changed to always load the middleware
> — @drbild

> Yes I know, if this has been changed, and asm89/stack-cors#11 or similar has merged + tagged, ping me back and I'll change that.
> — @barryvdh 

… but actually asm89/stack-cors#11 _did not_ change this. It is still not adding the `Vary: Origin` header _always_.

Over at https://github.com/barryvdh/laravel-cors/issues/20#issuecomment-50444205, the maintainer of this repo (@asm89) agreed that that would be sensible to do.

@asm89, would you be still open to doing that?

**Comment by typhonius** [comment]
Adding a note here that we're bumping into this with sites that use this library and have different requests from different origins being stored in Varnish cache. In line with what @wimleers is observing, when the request comes from the same origin, the response doesn't include a Vary header that then causes CORS blockages for future requests that receive the cached response.

By always adding `Vary: Origin`, we'll cache different responses for each origin and the issue should be resolved.

**Comment by marguskoiduste** [comment]
I thought I had the same issue. However, it turned out that Chrome does not support multi-domain CORS with conditional requests. This means that `Vary: Origin` is ignored if `ETag` header is present. For my case, the fix was just to remove the `ETag`. I found the solution here: https://bugs.chromium.org/p/chromium/issues/detail?id=453306

**Comment by asm89** [comment]
Sounds fair.

@wimleers Could you work on a pull request? Since this library has been stable for a long time, perhaps we should put the "always reply with `Vary: Origin`" behavior behind a new configuration option.

**Comment by mrbaileys** [comment]
Created a pull request that added an additional option 'alwaysSetVaryOrigin'. If not set (default), current behavior remains unchaged. When the flag is set, this library will add a Vary: Origin header to all responses.

**Comment by davidbarratt** [comment]
Can you all try out #68 and see if it resolves your problem? I think it should fix the cacheability without adding new configuration.

**Comment by barryvdh** [comment]
I think this should all be fixed now.
