### ISSUE TITLE
Packagist not auto-updating

### ISSUE THREAD

**Issue by GrahamCampbell** [asm89/stack-cors#59]
The v1.3.0 tag has not been picked up, since the packagist auto-update hooks are not setup.

<img width="241" alt="image" src="https://user-images.githubusercontent.com/2829600/71447908-d4c5d280-272c-11ea-8f55-67d8e9a7778c.png">

**Comment by barryvdh** [comment]
@asm89 could you check your packagist integration?

**Comment by barryvdh** [comment]
I manually updated for now.

**Comment by asm89** [comment]
@barryvdh Thanks for the ping (and ongoing maintenance!). Something was wrong indeed. Should be fixed now.

**Comment by asm89** [comment]
@barryvdh Added you as maintainer on packagist as well.
