### ISSUE TITLE
Only Vary the request when necessary

### ISSUE THREAD

**Issue by davidbarratt** [asm89/stack-cors#64]
**Problem**
If I set `allowedOrigins` to `*` and leave all of the other options to the default, I would expect to get a rsponse like this:
```
Access-Control-Allow-Origin: *
```
instead I get this:
```
Access-Control-Allow-Origin: https://example.com
Vary: Origin
```

I realize that some of the CORS headers need the origin to be set, like `Access-Control-Allow-Credentials`, but if this is the only one that is being set, it means the cache is being broken unnecssarily. 

**Proposed Solution**
To preserve caching, if possible, the middleware should seek to set the same value on every response, and not add/modify the `Vary` header. It should only the Vary the response if the config mandates it.

**Comment by barryvdh** [comment]
So the opposite of https://github.com/asm89/stack-cors/issues/49 ?

I understand the case, if you don't use credentials, I think * is probably fine and better for caching indeed.

**Comment by davidbarratt** [comment]
> So the opposite of #49 ?

Uhh... kind of. From reading #49 it seems a little misguided. If the the request **needs** to be varried by the `Origin` then it should **always** add it (even if it's not necessarily a cors request, as it could become one). If it doesn't need to be, it shouldn't be. I think adding this as configuration is __more__ confusing.

In other words, this logic doesn't make any sense:
https://github.com/asm89/stack-cors/blob/82ede75f64bd2801773d7179d63468dcf7cad526/src/Asm89/Stack/CorsService.php#L65
because if the request is missing the `Origin` header (for wahtever reason) or comes from the same `Origin` it gets cached as a non-cors request, which would break all subsequent cross-origin requests. :(

I think it should follow this logic:
```
if ( $config['supportsCredentials] === true || $config['allowedOrigins'] !== ['*']) {
  // Set or append `Origin` to `Vary` header on all requests.
}
```

**Comment by davidbarratt** [comment]
FYI: This is still an issue because of:
https://github.com/asm89/stack-cors/blob/561a5ee2a9b6ae912070e6c717f4eb606b1fc714/src/Asm89/Stack/Cors.php#L48-L50

**Comment by davidbarratt** [comment]
Lastly, we should deal with this:
https://github.com/asm89/stack-cors/blob/456655a26c462cf583a9b90d4bfe4fd6523ff48a/src/Cors.php#L48-L50

at a minimum, it should check that the method is `OPTIONS` first:
https://github.com/asm89/stack-cors/blob/456655a26c462cf583a9b90d4bfe4fd6523ff48a/src/CorsService.php#L70-L75

**Comment by barryvdh** [comment]
Can we close this now?

**Comment by davidbarratt** [comment]
> Can we close this now?

Yep! It looks so beautiful! :) Thank you so much!

**Comment by barryvdh** [comment]
Okay I've tagged a 2.0.0-beta1 so please test it out :)

**Comment by davidbarratt** [comment]
> Okay I've tagged a 2.0.0-beta1 so please test it out :)

Oh where was the breaking change?

**Comment by barryvdh** [comment]
Well, the behavior has changed a bit imho, not sure if that qualifies as actually breaking. Is that a problem?

**Comment by davidbarratt** [comment]
> Well, the behavior has changed a bit imho, not sure if that qualifies as actually breaking. Is that a problem?

I have no idea, I can submit the Drupal patch. :)

**Comment by davidbarratt** [comment]
Looking at https://semver.org/ it seems like this would be a minor since we didn't change the public API at all. The breaking change would be removing the methods we no longer use. :) but your call. :)

**Comment by davidbarratt** [comment]
I guess the question is: Does this change _break_ backwards compatability? It doesn't seem like it does. I could argue that it's actually a bug fix and not even a new feature.

**Comment by davidbarratt** [comment]
Seems like it would be wise to release a beta version of the point release (i.e. `1.4.0-beta1`) though.

**Comment by GrahamCampbell** [comment]
A breaking change to semantics is also a breaking change, even if there's no breaking changes to the signatures.

**Comment by GrahamCampbell** [comment]
2.0.0-beta1 was the right choice.

**Comment by davidbarratt** [comment]
> A breaking change to semantics is also a breaking change, even if there's no breaking changes to the signatures.

https://semver.org/ defines a breaking change as a change in the "Public API" not to the semantics, but true you may define the Public API however you want. :)

**Comment by GrahamCampbell** [comment]
A change to the semantics IS a breaking change to the public API...

**Comment by davidbarratt** [comment]
> A change to the semantics IS a breaking change to the public API...

well I'm not sure how anyone could argue with that level of circular reasoning.

**Comment by davidbarratt** [comment]
Here's the issue in Drupal's Queue
https://www.drupal.org/project/drupal/issues/3128982
