### ISSUE TITLE
Access control is unnecessary

### ISSUE THREAD

**Issue by davidbarratt** [asm89/stack-cors#65]
**Problem**
This library attempts to control access to ensure that the request meets the allowable criteria under the config. However, this isn't necessary because the browser already does this. The most restrictive thing you can do, is doing **nothing**. CORS is about _allowing_ things, not restricting them.

The preflight cannot even be cached because it has to varied by `Access-Control-Request-Headers`. However this isn't necessary, the config is the same regardless of what is requested.

**Proposed Solution**
Remove access checking which is unnecessary and breaks caching by forcing the request to be varied by the `Origin`.

**Comment by barryvdh** [comment]
The only case that access needs to be check if you're using both allowCredentials and a wilcard origin. Because this is not supported by the CORS spec, we return that exact origin. But that is probably the only case in which we actually need to check the header (and set Vary: origin)

**Comment by barryvdh** [comment]
Can you check out https://github.com/asm89/stack-cors/pull/70 ?
I think that solves it while taking into account dynamic Origins for supportsCredentials and patterns.

**Comment by davidbarratt** [comment]
> The only case that access needs to be check if you're using both allowCredentials and a wilcard origin. Because this is not supported by the CORS spec, we return that exact origin. But that is probably the only case in which we actually need to check the header (and set Vary: origin)

This case would always need the origin varried, but it doesn't need to return a failing response. If the preflight doesn't include [Access-Control-Allow-Credentials](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Credentials) it wont make the request, if it's a simple request, then the response becomes opaque. 

Though if the user is specifying a wildcard for the origins, then they wouldn't be able to get to the failed response in the first place becuase they are allowing it for all origins (regardless if the browser supports a response like that).

**Comment by barryvdh** [comment]
Yeah #70 always adds the Vary header for that case, and checks the origin before setting header. In the other case, no Vary is set and no check is done.
