### ISSUE TITLE
Problem with asm89/stack-cors 1.3.0, installing barryvdh/laravel-cors 

### ISSUE THREAD

**Issue by vblanco20** [asm89/stack-cors#80]
Hi! I am starting with CORS and I am following a tutorial to configure it. 
I`m working with Laravel Framework 7.7.1 and I have a problem to run "**_composer require barryvdh / laravel-cors_**", I would appreciate if you could give me a clue to solve it

When I run "**_composer require barryvdh / laravel-cors_**" I get the following error:
$ composer require barryvdh/laravel-corsUsing version ^2.0 for barryvdh/laravel-cors
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: don't install barryvdh/laravel-cors v2.0.0
    - Conclusion: don't install barryvdh/laravel-cors v2.0.0-beta3
    - Conclusion: don't install barryvdh/laravel-cors v2.0.0-beta2
    - Conclusion: don't install barryvdh/laravel-cors v2.0.0-beta1
    - Conclusion: remove asm89/stack-cors 1.3.0
    - Installation request for barryvdh/laravel-cors ^2.0 -> satisfiable by barryvdh/laravel-cors[2.0.x-dev, v2.0.0, v2.0.0-beta1, v2.0.0-beta2, v2.0.0-beta3].
    - Conclusion: don't install asm89/stack-cors 1.3.0
    - barryvdh/laravel-cors 2.0.x-dev requires asm89/stack-cors ^2 -> satisfiable by asm89/stack-cors[2.0.0, 2.0.0-beta1, 2.0.0-beta2, 2.0.0-beta3, 2.0.x-dev].
    - Can only install one of: asm89/stack-cors[2.0.0, 1.3.0].
    - Can only install one of: asm89/stack-cors[2.0.0-beta1, 1.3.0].
    - Can only install one of: asm89/stack-cors[2.0.0-beta2, 1.3.0].
    - Can only install one of: asm89/stack-cors[2.0.0-beta3, 1.3.0].
    - Can only install one of: asm89/stack-cors[2.0.x-dev, 1.3.0].
    - Installation request for asm89/stack-cors (locked at 1.3.0) -> satisfiable by asm89/stack-cors[1.3.0].

Installation failed, reverting ./composer.json to its original content.

**Comment by barryvdh** [comment]
Install fruitcake/laravel-cors.

**Comment by barryvdh** [comment]
And v2 of laravel-cors is using v2 of this library. Did you specify both directly?

**Comment by vblanco20** [comment]
Thanks for your answer! I didn't specify the versions.
I also tried with fruitcake/laravel-cors, but I had the same error, I suppose it must be due to the versions too.
Would I need to remove **_asm89/stack-cors 1.3.0_** version and reinstall it or install the corresponding version of **_laravel-cors_**? If it were the last option, what would be the version for **_laravel-cors_**

**Comment by barryvdh** [comment]
remove stack-cors and just install fruitcake/laravel-cors 2.x directly

**Comment by vblanco20** [comment]
Could you tell me the correct way to remove stack-cors, please. I am trying with **_composer remove vendor/stack-cors_** but it says "**_Nothing to install or update_**"

Sorry, I'm new with Laravel!!

**Comment by vblanco20** [comment]
I also tried with **_composer remove vendor/asm89/stack-cors_**

**Comment by vblanco20** [comment]
I could solved the problem. 
I removed **_fruitcake/laravel-cors_** and it also removed **_asm89/stack-cors (1.3.0)_**. 

_**fruitcake/laravel-cors (v1.0.6)**_ was already installed.

Thanks!!
