### ISSUE TITLE
Nullable header values bug

### ISSUE THREAD

**Issue by jetexe** [asm89/stack-cors#85]
Hi!

[PSR-7](https://www.php-fig.org/psr/psr-7/#31-psrhttpmessagemessageinterface) says that header must be `string` or `string[]` but this service sets `Access-Control-Allow-Origin` to `null` then `allowedOrigins` is `['*']`, `supportsCredentials` is `true` and `Origin` header doesn't  set.

I suggest to add additional check [here](https://github.com/asm89/stack-cors/blob/8d8f88b3b3830916be94292c1fbce84433efb1aa/src/CorsService.php#L149)

**Comment by tarampampam** [comment]
Ping @asm89

**Comment by tarampampam** [comment]
@barryvdh can you say when fixed version will be released?)

**Comment by barryvdh** [comment]
https://github.com/asm89/stack-cors/releases/tag/v2.0.3 is released now.
