### ISSUE TITLE
Add regex support in allowedOrigins

### ISSUE THREAD

**Issue by iBobik** [asm89/stack-cors#87]
I need to support review apps with dynamic domains.

This could be solved by allowedOrigins supporting regexp, or by second option allowedOriginRegEx only for regex.

It PR with this feature welcomed?

**Comment by barryvdh** [comment]
Can't you use allowedOriginsPatterns?

**Comment by iBobik** [comment]
Yes, I can. :-)

Sorry, I missed it.
